development:
  adapter: mysql2
  encoding: utf8
  database: prueba_concepto_development
  pool: 5
  username: pghumor
  password: ckP8t/2l


test:
  adapter: mysql2
  encoding: utf8
  database: prueba_concepto_development
  pool: 5
  username: pghumor
  password: ckP8t/2l
