development:
  adapter: mysql2
  encoding: utf8
  database: prueba_concepto_development
  pool: 5
  username: pghumor
  password: --PASSWORD--


test:
  adapter: mysql2
  encoding: utf8
  database: prueba_concepto_development
  pool: 5
  username: pghumor
  password: --PASSWORD--


production:
  adapter: mysql2
  encoding: utf8
  database: prueba_concepto_development
  pool: 5
  username: pghumor
  password: --PASSWORD--
