development:
  adapter: mysql2
  encoding: utf8
  database: prueba_concepto_development
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock


test:
  adapter: mysql2
  encoding: utf8
  database: prueba_concepto_development
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock
