default: &default
  adapter: mysql2
  encoding: utf8
  database: pghumor_live
  pool: 5
  username: pghumor
  password: <%= Rails.application.secrets[:password] %>

development: *default
test: *default
production: *default
