# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0f0870bec0562fec43777e1abce56beb11799d2035197d91ec40f6e63659b5a5aa7ec19dd14135a9e4c2bdeaa0c74ef6ce2ec6c0bc892ccc900d36f13bf572f

test:
  secret_key_base: 61f1e8d85798e25b7bb6d29b0551b41feec1288d7c309d20a6ac16994fa5276f2fd7bfe894878b75523ff3fda9cb0713c91d8b040755591fd52f48ff7f127532

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
